// POST /signup route with bcrypt password hashing and input validation
const express = require('express');
const bcrypt = require('bcrypt');
const db = require('../db');

const router = express.Router();

// Allowlist regex for username (injection prevention)
const usernameRegex = /^[a-zA-Z0-9_-]+$/;

/**
 * POST /signup
 * Register new user with bcrypt-hashed password
 * Returns 201 on success, 400 on validation error, 409 on duplicate username
 */
router.post('/signup', async (req, res) => {
  const { username, password } = req.body;

  // Validate input fields are non-empty strings
  if (!username || typeof username !== 'string' || !password || typeof password !== 'string') {
    return res.status(400).json({
      success: false,
      message: 'Validation error'
    });
  }

  // Validate username length and format (allowlist regex)
  if (username.length < 3 || username.length > 50 || !usernameRegex.test(username)) {
    return res.status(400).json({
      success: false,
      message: 'Validation error'
    });
  }

  // Validate password length (minimum 8 characters)
  if (password.length < 8) {
    return res.status(400).json({
      success: false,
      message: 'Validation error'
    });
  }

  // Check for duplicate username
  const existingUser = db.findOne('username', username);
  if (existingUser) {
    return res.status(409).json({
      success: false,
      message: 'User already exists'
    });
  }

  try {
    // Hash password with bcrypt cost factor 12
    const passwordHash = await bcrypt.hash(password, 12);

    // Save user (ID generated by db.save)
    db.save({
      username,
      passwordHash
    });

    // Success - never echo password or hash in response
    return res.status(201).json({
      success: true,
      message: 'User created'
    });
  } catch (error) {
    // Generic error (don't expose internals)
    return res.status(500).json({
      success: false,
      message: 'Server error'
    });
  }
});

module.exports = router;
